### ISSUE TITLE
Error handling rework

### ISSUE THREAD

**Issue by thedjchi** [RahulR100/mcstatusbot#42]
Might be worth implementing [node-retry](https://github.com/tim-kos/node-retry) to reduce network errors. Could make a function that wraps any api/db requests with the retry class.

Additionally, we should implement an error handling function that:
- takes an error and context as an argument
- ignores the error if the type is RateLimitError
- logs the request in a separate channel as a network error if the code is ETIMEDOUT
- logs the error otherwise, using the context to determine the log output

This will clean up the code in most functions and move the logging entirely to one file.

Then we can add a LOG_LEVEL env variable to specify whether network errors and rate limit errors show up in the console.

**Comment by RahulR100** [comment]
Considered complete with latest backend update.
