### ISSUE TITLE
Server voice channels say "offline", even though the server is running and it's not until after running /status confirms the bot to know the server is online (and update)

### ISSUE THREAD

**Issue by Kharakhov** [RahulR100/mcstatusbot#51]
It would seem the voice channels are bugged, because they keep saying offline even though the server is online. I did /status and then the bot updated the channels. I know that the issue is technically resolved but I'd still rather have it update automatically? 
As for what caused the bug, I think it might be the server automatically restarting every so often. 
![Screenshot from 2023-11-10 08-32-15](https://github.com/RahulR100/mcstatusbot/assets/150427673/412e5938-f772-4930-a2c3-71688a2daed0)
![Screenshot from 2023-11-10 08-33-07](https://github.com/RahulR100/mcstatusbot/assets/150427673/9ce20d50-77e8-4541-9e40-8f2cbad7640f)

**Comment by RahulR100** [comment]
Thank you for letting us know. Indeed it seems like some cache validation issue here. Will let you know once we have pushed a fix.

**Comment by RahulR100** [comment]
I've cleared the server cache on the backend. Is this a one off issue or are you seeing this happen multiple times?

**Comment by Kharakhov** [comment]
I've seen it a few more times, but it seems to work fine now. Thanks!
