### ISSUE TITLE
Bot claims server is offline with no players even though It's online with players

### ISSUE THREAD

**Issue by RaikonJP** [RahulR100/mcstatusbot#53]
Just like the title says. The bot says the server is offline with 0 players even though it's online with players. 

Not sure why this is happening maybe perhaps cause it's an Aternos.me server but I don't why this would be a problem. 
Any help would be appreciated

**Comment by RaikonJP** [comment]
![image_2024-01-06_235525742](https://github.com/RahulR100/mcstatusbot/assets/155857341/f495fa94-eab2-44fa-abd9-c2c277cb9db5)

**Comment by SanchitGamer** [comment]
![image](https://github.com/RahulR100/mcstatusbot/assets/150579027/9e98ae55-8cae-4cd2-8926-834d3c35a030)
Even I left server but it didn't change status

**Comment by derjoei99** [comment]
I have the same problem. also an aternos server. also still shows as offline when someone is inside!

**Comment by SanchitGamer** [comment]
> I have the same problem. also an aternos server. also still shows as offline when someone is inside!

i am in flora mc

**Comment by RahulR100** [comment]
We are looking into this right now. Seems like it fails randomly and only on certain servers. From past experience this is an internal cache problem. I will keep you updated on solutions we are trying. Thanks for informing us and let us know if this problem is recurring.

**Comment by RahulR100** [comment]
Did the status update eventually after you joined the server? or did it stay offline for > 10 mins? (Server statuses may take up to 10 mins to update. Unfortunately this is a discord limitation).

**Comment by Ferogreywolf7** [comment]
Same here

**Comment by RahulR100** [comment]
Hey @Ferogreywolf7! Were you using the voice channels or the `/status` command? Also, what was the address of the server you were trying to monitor?

**Comment by Ferogreywolf7** [comment]
I was using the voice channels. The IP address is mcrlcraft.aternos.me

**Comment by Ferogreywolf7** [comment]
So it appears to be a problem with aternos servers

**Comment by RahulR100** [comment]
Ah yes. Aternos servers are currently unreliable due to strategies implemented by Aternos on their end. Most problematic is that Aternos suspends servers after they have been inactive for a while, and only brings them online when a player joins. This causes problems for our bot. In most cases, our bot will recognize that the server has come back online after a few minutes and will reflect the correct status.

Solving this problem is in our pipeline but we don't expect to push a solution anytime soon.
