### ISSUE TITLE
Add multiple language support

### ISSUE THREAD

**Issue by RahulR100** [RahulR100/mcstatusbot#57]
All language support for:
- Spanish
- German
- Mandarin
- Russian

**Comment by idkslz** [comment]
Can I help with russian?

**Comment by RahulR100** [comment]
That would be awesome! I will let you know when the localization system is ready, after which any help would be highly appreciated.

**Comment by MohamedDXD** [comment]
hi

**Comment by RahulR100** [comment]
Multi language support is complete. Add languages using the contributing guide. German is currently the only language but the others will follow in the next update. For now I will close this issue.
