### ISSUE TITLE
Bot Offline 

### ISSUE THREAD

**Issue by ImAGh0st** [RahulR100/mcstatusbot#60]
Bot is offline for the past 6 hours for my server,
Anything I can do?

I tried reinviting it,
Giving it a new admin role etc..
Nothing seems to work.
![Screenshot_98](https://github.com/RahulR100/mcstatusbot/assets/168428460/338cc71d-1dd7-4069-85b1-f972aeb0b4ca)

**Comment by RahulR100** [comment]
Its coming back on now. Looking into what happened.

**Comment by ImAGh0st** [comment]
Its not just yours, most of the MC Status bots are/we're offline apparently

**Comment by RahulR100** [comment]
Yeah the server went down earlier in the morning. There seems to be something in the sharding code that is causing it to memory leak randomly and eat insane amounts of memory. Still trying to find a fix.
